name: tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: [README, TODO, PROBLEMS]
  pull_request:
    paths-ignore: [README, TODO, PROBLEMS]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs: # Docs: <https://git.io/JvxXE>
  docker-build:
    name: Build the docker image
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: hydra:ci
